name: 1.Build Armbian LXFce Trixie Uefi-x86
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune -a -f
      
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y 7zip curl git wget ca-certificates binutils debootstrap \
            squashfs-tools xz-utils lz4 zstd xorriso mtools rsync grub-efi-amd64-bin \
            grub-pc-bin grub-common qemu-user-static binfmt-support \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu build-essential

      - name: Download, Decompress and Build
        run: |
          chmod +x compile.sh
          ./compile.sh build BOARD=uefi-x86 BRANCH=edge RELEASE=trixie \
           EXPERT=yes BUILD_DESKTOP=yes BUILD_MINIMAL=no \
           DESKTOP_APPGROUPS_SELECTED= DESKTOP_ENVIRONMENT=xfce \
           DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base \
           KERNEL_BTF=no KERNEL_CONFIGURE=no KERNEL_GIT=shallow \
           DOCKER_ARMBIAN=no

      - name: Upload Armbian.iMG
        uses: actions/upload-artifact@v4
        with:
          name: Armbian.LXFce.Trixie.Uefi-x86
          path: output/images/*.img*
          if-no-files-found: error
          retention-days: 15
